version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-marketing-container
    depends_on:
      - db
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    restart: always

volumes:
  mysql_data:
